source 'https://rubygems.org'

gem 'jekyll'

group :jekyll_plugins do
    gem 'jekyll-paginate'
    gem 'jekyll-postfiles'
end

# gem 'github-pages'

# group :plugins do
#   gem 'jekyll-livereload'
# end
